# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'capybara'
require 'capybara/rspec'
require 'capybara/dsl'
require 'vcr'
require 'fakeweb'
require 'rspec/its'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.include Capybara::DSL
  config.treat_symbols_as_metadata_keys_with_true_values = true

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].each {|f| require f}
Dir["#{File.dirname(__FILE__)}/shared/**/*.rb"].each {|f| require f}

NaskEpp_PROTOCOL_VERSION = "3.0"

require 'nask_epp'

NaskEpp::SERVER = "qregistry.nask.waw.pl"
NaskEpp::PATH = "/registry/epp"
NaskEpp::CA_FILE = "spec/ssl/root.pem"
NaskEpp::CERT = "spec/ssl/0.pem"
NaskEpp::KEY = "spec/ssl/klucz.pem"

VCR.configure do |c|
  c.cassette_library_dir = 'spec/cassettes'
  c.hook_into :fakeweb
  c.configure_rspec_metadata!
  %w(
    NASK_EPP_LOGIN1
    NASK_EPP_PASSWORD1
    NASK_EPP_PASSWORD_URI_ENCODED1
    NASK_EPP_PREFIX1

    NASK_EPP_LOGIN2
    NASK_EPP_PASSWORD2
    NASK_EPP_PASSWORD_URI_ENCODED2
    NASK_EPP_PREFIX2

    CONTACT_1_EMAIL_PASSWORD

    CONTACT1_NAME
    CONTACT1_STREET
    CONTACT1_CITY
    CONTACT1_PROVINCE
    CONTACT1_ZIP_CODE
    CONTACT1_COUNTRY
    CONTACT1_PHONE
    CONTACT1_EMAIL

    CONTACT2_NAME
    CONTACT2_STREET
    CONTACT2_PHONE
    CONTACT2_EMAIL

    CONTACT3_NAME
    CONTACT3_STREET
    CONTACT3_PHONE
    CONTACT3_EMAIL

    CONTACT4_NAME
    CONTACT4_STREET
    CONTACT4_PHONE
    CONTACT4_EMAIL

    CONTACT5_NAME
    CONTACT5_STREET
    CONTACT5_PHONE
    CONTACT5_EMAIL

    CONTACT6_NAME
    CONTACT6_EMAIL

    CONTACT7_NAME
    CONTACT7_EMAIL

    CONTACT8_NAME
    CONTACT8_EMAIL

    CONTACT9_EMAIL
  ).each do |sensitive_variable|
    c.filter_sensitive_data(sensitive_variable) { ENV[sensitive_variable] }
  end
end
